###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Alice Alonso, Damien Delforge, Marnik Vanclooster'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = 'https://AliceAl.github.io/guide4Researchers2'
html_css_files = ['mystnb.4510f1fc1dee50b3e5859aac5469c37c29e427902b24a333a5f9fcb2f0b3ac41.css', 'basic.css', 'pygments.css', 'sphinx-design.4cbf315f70debaebd550c87a6162cf0f.min.css', 'copybutton.css', 'sphinx-thebe.css', 'togglebutton.css', 'styles/theme.css', 'styles/bootstrap.css', 'styles/sphinx-book-theme.css', 'styles/pydata-sphinx-theme.css', 'vendor/fontawesome/6.5.2/css/all.min.css']
html_favicon = ''
html_js_files = ['sphinx_highlight.js', 'documentation_options.js', 'searchtools.js', 'clipboard.min.js', 'copybutton.js', 'design-tabs.js', 'language_data.js', 'copybutton_funcs.js', 'sphinx-thebe.js', 'doctools.js', 'togglebutton.js', 'scripts/sphinx-book-theme.js', 'scripts/bootstrap.js', 'scripts/pydata-sphinx-theme.js', 'vendor/fontawesome/6.5.2/js/all.min.js']
html_logo = '~/Sync/ADSCIAN/02_communication/logos partnerslogo/UCLouvain_format_jpg_quadri.png'
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': '', 'jupyterhub_url': '', 'thebe': False, 'colab_url': ''}, 'path_to_docs': '', 'repository_url': 'https://github.com/executablebooks/jupyter-book', 'repository_branch': 'master', 'extra_footer': '', 'home_page_in_toc': True, 'announcement': '', 'analytics': {'google_analytics_id': ''}, 'use_repository_button': False, 'use_edit_page_button': False, 'use_issues_button': False}
html_title = 'Guide for researchers'
latex_engine = 'pdflatex'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'force'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
